//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registro.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LezioniStudenti
    {
        public int LezioniStudentiId { get; set; }
        public int LezioneId { get; set; }
        public int StudenteId { get; set; }
        public bool Presente { get; set; }
    
        public virtual Lezione Lezione { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
